export const ROUTES = {
    home: '/',
    category: '/category',
    product: '/product/:id',
    cart: '/cart',
    about: '/about',
    aboutCompany: '/about-company',
    contacts: '/contacts',
    login: '/login',
    registration: '/registration',
    lookbook: '/lookbook',
    news: '/news',
    articles: '/articles',
    toCustomers: '/to-customers',
    toWholesalers: '/wholesalers',
};