export const ROUTES = {
    home: '/',
    category: '/category/:id/products',
    product: '/product/:id',
    cart: '/cart',
    about: '/about',
    aboutCompany: '/about-company',
    contacts: '/contacts',
    login: '/login',
    registration: '/registration',
    news: '/news',
    newsById: '/news/:id',
    toCustomers: '/to-customers',
    toWholesalers: '/wholesalers',
    search: '/search/:search',
};